spring:
  application:
     name: accounts-service
  jpa:
     hibernate:
        ddl-auto: update
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: WARN
