spring:
  application:
     name: webUI
eureka:
  client:
    registerWithEureka: false
    registryFetchIntervalSeconds: 10
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
logging:
  level:
     io:
        pivotal: DEBUG
     org:
        springframework:
           web: WARN
           cloud: WARN
     com:
       netflix:
         hystrix: DEBUG
pivotal:
  accountsService:
    name: accounts-service
  summary:
    quotes: 3
    symbols:
      it: EMC,ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK
