spring:
  profiles.active: local
  application:
     name: accounts
  jpa:
     hibernate:
        ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://${vcap.services.eureka-service.credentials.uri:127.0.0.1:8761}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost} 
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

---
spring:
  profiles: local
server:
  port: 8082
eureka:
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
eureka:
  instance:
     nonSecurePort: 80
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex'     
---        
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: WARN