spring:
  profiles.active: local
  application:
     name: webUI
eureka:
  client:
    registerWithEureka: false
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://${vcap.services.eureka-service.credentials.uri:127.0.0.1:8761}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost} 
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n" 
---
spring:
  profiles: local
  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8080
eureka:
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update
eureka:
  instance:
    nonSecurePort: 80
---        
logging:
  level:
     io:
        pivotal: DEBUG
     org:
        springframework:
           web: WARN
           cloud: WARN
     com:
        netflix: FATAL
