spring:
  profiles.active: local
  application:
     name: quotes
eureka:
  client:
    serviceUrl:
      defaultZone: http://${vcap.services.eureka-service.credentials.uri:127.0.0.1:8761}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost} 
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"
---
spring:
  profiles: local
server:
  port: 8083
eureka:
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
  sleuth:
    log:
      json:
        enabled: true
eureka:
  instance: 
    nonSecurePort: 80
---        
logging:
  level:
     io:
        pivotal: INFO
     com:
        netflix: WARN
